global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-node-1:7001', 'redis-node-2:7002', 'redis-node-3:7003', 'redis-node-4:7004', 'redis-node-5:7005']